"""Provider-specific custom agent generation."""

from __future__ import annotations

import tempfile
import unittest
from pathlib import Path

from agentkit import agents


EXPECTED_CODEX_AGENT_PATHS = {
    ".codex/agents/explorer.toml",
    ".codex/agents/planner.toml",
    ".codex/agents/implementer.toml",
    ".codex/agents/reviewer.toml",
}


class CodexAgentGenerationTests(unittest.TestCase):
    def test_generate_writes_codex_agent_files_and_check_passes(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp).resolve()

            changed = agents.generate(root, provider="codex")

            self.assertEqual(set(changed), EXPECTED_CODEX_AGENT_PATHS)
            for rel_path in EXPECTED_CODEX_AGENT_PATHS:
                text = (root / rel_path).read_text(encoding="utf-8")
                name = Path(rel_path).stem
                self.assertIn("Generated by agentkit", text)
                self.assertIn(f'name = "{name}"', text)
                self.assertIn("description = ", text)
                self.assertIn("developer_instructions = ", text)
            self.assertEqual(agents.generate(root, provider="codex", check=True), [])

    def test_check_fails_on_drift(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp).resolve()
            agents.generate(root, provider="codex")

            path = root / ".codex/agents/reviewer.toml"
            path.write_text(path.read_text(encoding="utf-8") + "# drift\n", encoding="utf-8")

            self.assertIn(".codex/agents/reviewer.toml", agents.generate(root, provider="codex", check=True))

    def test_existing_unmarked_agent_file_is_not_overwritten(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp).resolve()
            path = root / ".codex/agents/explorer.toml"
            path.parent.mkdir(parents=True)
            path.write_text('name = "mine"\n', encoding="utf-8")

            with self.assertRaises(agents.ProtectedAgentFile):
                agents.generate(root, provider="codex")

            self.assertEqual(path.read_text(encoding="utf-8"), 'name = "mine"\n')
            self.assertFalse((root / ".codex/agents/planner.toml").exists())

    def test_unsupported_provider_fails_clearly(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp).resolve()

            with self.assertRaises(agents.UnsupportedProvider) as ctx:
                agents.generate(root, provider="claude")

            self.assertIn("unsupported agent provider: claude", str(ctx.exception))


if __name__ == "__main__":
    unittest.main()
