#!/usr/bin/env python3
"""Generate provider-specific custom agents.

This is intentionally separate from adapter sync. Skills are provider-agnostic
instructions; custom/subagents are provider-specific delegated workers.
"""

from __future__ import annotations

import textwrap
from dataclasses import dataclass
from pathlib import Path

SUPPORTED_PROVIDERS = ("codex",)
GENERATED_MARKER = "Generated by agentkit"
GENERATED = (
    "Generated by agentkit from .agents; do not edit directly. "
    "Run 'agentkit agents generate --provider codex'."
)


class AgentGenerationError(ValueError):
    """Base exception for custom agent generation failures."""


class UnsupportedProvider(AgentGenerationError):
    """Raised when a provider has no verified custom-agent generator."""

    def __init__(self, provider: str):
        self.provider = provider
        super().__init__(
            f"unsupported agent provider: {provider}. Supported providers: "
            + ", ".join(SUPPORTED_PROVIDERS)
        )


class ProtectedAgentFile(AgentGenerationError):
    """Raised when generation would overwrite a user-owned agent file."""

    def __init__(self, paths: list[str]):
        self.paths = paths
        super().__init__(
            "will not overwrite existing custom agent file(s) without an "
            f"agentkit marker: {', '.join(paths)}"
        )


@dataclass(frozen=True)
class CodexAgent:
    name: str
    description: str
    instructions: str


CODEX_AGENTS = [
    CodexAgent(
        name="explorer",
        description=(
            "Read-heavy project exploration agent for mapping code, docs, "
            "constraints, and risks without changing files."
        ),
        instructions="""
            You are the explorer subagent for this project.

            Follow AGENTS.md and the relevant .agents/skills/**/SKILL.md files.
            Focus on discovery: inspect files, map architecture, identify constraints,
            and summarize findings with file references.
            Do not modify files unless the parent explicitly asks you to.
            Return concise findings, open questions, and suggested next inspection paths.
        """,
    ),
    CodexAgent(
        name="planner",
        description=(
            "Planning agent for turning a clear objective into scoped steps, "
            "tradeoffs, risks, and verification."
        ),
        instructions="""
            You are the planner subagent for this project.

            Follow AGENTS.md and the relevant .agents/skills/**/SKILL.md files.
            Convert the objective into a practical implementation plan with boundaries,
            dependencies, risks, and verification.
            Prefer the repository's existing architecture and conventions.
            Do not edit files unless the parent explicitly asks you to.
            Return a concise plan that the parent can execute or refine.
        """,
    ),
    CodexAgent(
        name="implementer",
        description=(
            "Implementation agent for scoped code and documentation changes with "
            "local verification."
        ),
        instructions="""
            You are the implementer subagent for this project.

            Follow AGENTS.md and the relevant .agents/skills/**/SKILL.md files.
            Make only the scoped changes requested by the parent.
            Preserve user changes and avoid unrelated refactors.
            Run focused verification when feasible and report exact commands and results.
            Return changed files, important decisions, and any remaining risks.
        """,
    ),
    CodexAgent(
        name="reviewer",
        description=(
            "Review agent focused on correctness, regressions, security, and "
            "missing tests."
        ),
        instructions="""
            You are the reviewer subagent for this project.

            Follow AGENTS.md and the relevant .agents/skills/**/SKILL.md files.
            Review with a bug-finding stance: prioritize correctness, behavior
            regressions, security issues, and missing tests.
            Ground findings in file and line references where possible.
            Do not modify files unless the parent explicitly asks you to.
            Return findings ordered by severity, followed by open questions and test gaps.
        """,
    ),
]


def _toml_string(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _toml_multiline(value: str) -> str:
    return '"""\n' + textwrap.dedent(value).strip() + '\n"""'


def codex_agent_text(agent: CodexAgent) -> str:
    """Render one standalone Codex custom-agent TOML file."""
    return "\n".join(
        [
            f"# {GENERATED}",
            "",
            f"name = {_toml_string(agent.name)}",
            f"description = {_toml_string(agent.description)}",
            f"developer_instructions = {_toml_multiline(agent.instructions)}",
            "",
        ]
    )


def codex_agent_outputs(root: Path) -> dict[Path, str]:
    root = Path(root)
    return {root / ".codex/agents" / f"{agent.name}.toml": codex_agent_text(agent) for agent in CODEX_AGENTS}


def _read_text(path: Path) -> str | None:
    if not path.exists() or path.is_dir():
        return None
    return path.read_text(encoding="utf-8")


def _has_marker(text: str | None) -> bool:
    return bool(text and GENERATED_MARKER in text)


def _rel(root: Path, path: Path) -> str:
    return str(path.relative_to(root))


def generate(root: Path, provider: str, check: bool = False) -> list[str]:
    """Generate or check provider-specific custom agents.

    Returns changed paths when writing and mismatched paths when checking.
    """
    root = Path(root).resolve()
    provider = provider.lower()
    if provider != "codex":
        raise UnsupportedProvider(provider)

    outputs = codex_agent_outputs(root)

    if check:
        mismatches: list[str] = []
        for path, expected in sorted(outputs.items(), key=lambda kv: str(kv[0])):
            current = _read_text(path)
            rel = _rel(root, path)
            if current is None:
                mismatches.append(f"{rel} is missing")
            elif not _has_marker(current):
                mismatches.append(f"{rel} exists but is not generated by agentkit")
            elif current != expected:
                mismatches.append(rel)
        return mismatches

    conflicts = [
        _rel(root, path)
        for path in sorted(outputs)
        if (current := _read_text(path)) is not None and not _has_marker(current)
    ]
    if conflicts:
        raise ProtectedAgentFile(conflicts)

    changed: list[str] = []
    for path, expected in sorted(outputs.items(), key=lambda kv: str(kv[0])):
        if _read_text(path) != expected:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(expected, encoding="utf-8")
            changed.append(_rel(root, path))
    return changed
