#!/usr/bin/env python3
"""Generate provider-specific agent adapters from AGENTS.md and .agents.

The engine is parameterized by a target project root, so the same logic works in
any project. Canonical sources live under ``<root>/.agents`` and ``<root>/AGENTS.md``;
generated adapters are written under ``<root>``. Project-specific literals (the
project name used in path placeholders and the Kiro agent name) are read from
``.agents/project.json``.
"""

from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any

GENERATED = "Generated by agentkit from .agents; do not edit directly. Run 'agentkit sync'."


# --------------------------------------------------------------------------- #
# Project facts
# --------------------------------------------------------------------------- #
def load_json(root: Path, relative_path: str) -> dict[str, Any]:
    with (root / relative_path).open(encoding="utf-8") as handle:
        return json.load(handle)


def project_name(root: Path) -> str:
    path = root / ".agents/project.json"
    if path.exists():
        try:
            return json.loads(path.read_text(encoding="utf-8")).get("name") or root.name
        except (OSError, ValueError):
            pass
    return root.name


def placeholder_for(name: str) -> str:
    return f"/path/to/{name}"


# --------------------------------------------------------------------------- #
# MCP helpers
# --------------------------------------------------------------------------- #
def command_args(server: dict[str, Any], target: str, placeholder: str) -> list[str]:
    replacement = placeholder if target == "codex" else "."
    return [str(arg).replace("${REPO_ROOT}", replacement) for arg in server.get("args", [])]


def cwd_value(server: dict[str, Any], target: str, placeholder: str) -> str | None:
    cwd = server.get("cwd")
    if not cwd:
        return None
    return str(cwd).replace("${REPO_ROOT}", placeholder if target == "codex" else ".")


def enabled_servers(mcp: dict[str, Any]) -> list[dict[str, Any]]:
    return [server for server in mcp["servers"] if server.get("enabledByDefault", False)]


def mcp_server_for_json(server: dict[str, Any], target: str, placeholder: str) -> dict[str, Any]:
    if server["transport"] == "http":
        return {"type": "http", "url": server["url"]}
    generated: dict[str, Any] = {
        "command": server["command"],
        "args": command_args(server, target, placeholder),
    }
    cwd = cwd_value(server, target, placeholder)
    if cwd:
        generated["cwd"] = cwd
    if server.get("envVars"):
        generated["env"] = {name: f"${{{name}}}" for name in server["envVars"]}
    return generated


def mcp_servers_json(mcp: dict[str, Any], target: str, placeholder: str) -> dict[str, Any]:
    return {
        "__generated": GENERATED,
        "mcpServers": {
            server["name"]: mcp_server_for_json(server, target, placeholder)
            for server in enabled_servers(mcp)
        },
    }


def mcp_server_for_opencode(server: dict[str, Any], placeholder: str) -> dict[str, Any]:
    if server["transport"] == "http":
        generated: dict[str, Any] = {"type": "remote", "url": server["url"], "enabled": True}
        if server.get("envVars"):
            generated["headers"] = {name: f"{{env:{name}}}" for name in server["envVars"]}
        return generated
    generated = {
        "type": "local",
        "command": [server["command"], *command_args(server, "opencode", placeholder)],
        "enabled": True,
    }
    cwd = cwd_value(server, "opencode", placeholder)
    if cwd:
        generated["cwd"] = cwd
    if server.get("envVars"):
        generated["environment"] = {name: f"{{env:{name}}}" for name in server["envVars"]}
    return generated


def opencode_permission(permissions: dict[str, Any]) -> dict[str, Any]:
    decision_map = {"allow": "allow", "prompt": "ask", "deny": "deny"}
    bash: dict[str, str] = {}
    for decision, action in decision_map.items():
        for rule in permissions["rules"].get(decision, []):
            bash[" ".join(rule) + "*"] = action
    return {"bash": bash}


def opencode_config(mcp: dict[str, Any], permissions: dict[str, Any], placeholder: str) -> dict[str, Any]:
    return {
        "$schema": "https://opencode.ai/config.json",
        "mcp": {
            server["name"]: mcp_server_for_opencode(server, placeholder)
            for server in enabled_servers(mcp)
        },
        "permission": opencode_permission(permissions),
    }


# --------------------------------------------------------------------------- #
# Codex / Claude / Kiro
# --------------------------------------------------------------------------- #
def quote_toml(value: str) -> str:
    return json.dumps(value)


def codex_config_example(mcp: dict[str, Any], placeholder: str) -> str:
    lines = [
        f"# {GENERATED}",
        f"# Copy this file to .codex/config.toml and replace {placeholder} with the "
        "absolute path to your local checkout.",
        "",
    ]
    for server in mcp["servers"]:
        name = server["name"]
        lines.append(f"[mcp_servers.{name}]")
        lines.append(f"enabled = {str(server.get('enabledByDefault', False)).lower()}")
        lines.append(f"required = {str(server.get('required', False)).lower()}")
        if server["transport"] == "http":
            lines.append(f"url = {quote_toml(server['url'])}")
        else:
            lines.append(f"command = {quote_toml(server['command'])}")
            lines.append(
                "args = [" + ", ".join(quote_toml(a) for a in command_args(server, "codex", placeholder)) + "]"
            )
        if server.get("envVars"):
            lines.append("env_vars = [" + ", ".join(quote_toml(n) for n in server["envVars"]) + "]")
        cwd = cwd_value(server, "codex", placeholder)
        if cwd:
            lines.append(f"cwd = {quote_toml(cwd)}")
        if server.get("startupTimeoutSec"):
            lines.append(f"startup_timeout_sec = {int(server['startupTimeoutSec'])}")
        lines.append(f"default_tools_approval_mode = {quote_toml(server.get('approval', 'prompt'))}")
        lines.append("")
        for tool_name, approval in sorted(server.get("toolApprovals", {}).items()):
            lines.append(f"[mcp_servers.{name}.tools.{tool_name}]")
            lines.append(f"approval_mode = {quote_toml(approval)}")
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def codex_rules(permissions: dict[str, Any]) -> str:
    lines = [
        f"# {GENERATED}",
        "# Git inspection and staging are routine. History, remote, branch-changing,",
        "# and destructive operations must ask first.",
    ]
    for decision in ("allow", "prompt", "deny"):
        rules = permissions["rules"].get(decision, [])
        if not rules:
            continue
        lines.append("")
        for pattern in rules:
            lines.append(f'prefix_rule(pattern={json.dumps(pattern)}, decision="{decision}")')
    return "\n".join(lines).rstrip() + "\n"


def claude_settings(permissions: dict[str, Any]) -> dict[str, Any]:
    allow = ["Bash(" + " ".join(rule) + ":*)" for rule in permissions["rules"]["allow"]]
    ask = ["Bash(" + " ".join(rule) + ":*)" for rule in permissions["rules"]["prompt"]]
    return {"__generated": GENERATED, "permissions": {"allow": allow, "ask": ask, "deny": []}}


def kiro_agent(permissions: dict[str, Any], name: str) -> dict[str, Any]:
    # No "__generated" marker: the JSON is validated against Kiro's agent schema.
    # toolsSettings.shell maps the git permission policy (allow -> allowedCommands,
    # deny -> deniedCommands); prompt rules fall through to per-command approval.
    def regexes(decision: str) -> list[str]:
        return ["^" + " ".join(rule) + r"\b" for rule in permissions["rules"].get(decision, [])]

    return {
        "name": f"{name}-maintainer",
        "description": (
            f"Repository maintenance agent for {name}. Follows the canonical AGENTS.md "
            "and .agents context with git-permission parity from .agents/permissions.json."
        ),
        "prompt": (
            "Follow AGENTS.md and the relevant .agents/skills/**/SKILL.md as the canonical "
            "repository agent context. Steering files under .kiro/steering delegate back to "
            "AGENTS.md and .agents. Do not weaken repository safety rules."
        ),
        "tools": ["read", "write", "shell", "grep", "glob", "code"],
        "resources": [
            "file://AGENTS.md",
            "file://.kiro/steering/agent-context.md",
            "file://.kiro/steering/mcp-and-permissions.md",
            "skill://.kiro/skills/**/SKILL.md",
        ],
        "toolsSettings": {"shell": {"allowedCommands": regexes("allow"), "deniedCommands": regexes("deny")}},
    }


# --------------------------------------------------------------------------- #
# Build & apply
# --------------------------------------------------------------------------- #
def build_outputs(root: Path) -> tuple[dict[Path, str], dict[Path, dict[str, Any]]]:
    mcp = load_json(root, ".agents/mcp/servers.json")
    permissions = load_json(root, ".agents/permissions.json")
    name = project_name(root)
    ph = placeholder_for(name)

    def R(rel_path: str) -> Path:
        return root / rel_path

    text: dict[Path, str] = {}
    jsonf: dict[Path, dict[str, Any]] = {}

    text[R(".codex/config.example.toml")] = codex_config_example(mcp, ph)
    text[R(".codex/rules/git-approval.rules")] = codex_rules(permissions)
    text[R("CLAUDE.md")] = (
        f"<!-- {GENERATED} -->\n# Claude Adapter\n\n"
        "Read and follow `AGENTS.md` and `.agents/**`; those files are the canonical "
        "repository agent context. Do not duplicate or weaken their safety rules here.\n\n"
        "Project-local skills are exposed through `.claude/skills`, which is a generated "
        "symlink to `.agents/skills`.\n"
    )
    text[R(".kiro/steering/agent-context.md")] = (
        f"<!-- {GENERATED} -->\n# Agent Context\n\n"
        "Use `AGENTS.md` as the canonical repository instruction file. Use `.agents/skills`, "
        "`.agents/mcp/servers.json`, `.agents/permissions.json`, and "
        "`.agents/provider-overrides.json` for canonical skills, MCP metadata, permission "
        "rules, and provider gaps.\n"
    )
    text[R(".kiro/steering/mcp-and-permissions.md")] = (
        f"<!-- {GENERATED} -->\n# MCP And Permissions\n\n"
        "MCP server definitions come from `.agents/mcp/servers.json`. Credentials belong in "
        "local `.env.mcp`, not committed adapter files. Git inspection and staging are "
        "routine; git history, remote, branch-changing, and destructive operations require "
        "confirmation according to `.agents/permissions.json`.\n"
    )
    text[R(".antigravity/README.md")] = (
        f"<!-- {GENERATED} -->\n# Antigravity Adapter\n\n"
        "This repository treats `AGENTS.md` and `.agents/**` as canonical. Antigravity CLI "
        "support is conservative because project settings paths may change quickly. When `agy` "
        "is installed, validate locally that it reads `AGENTS.md` from the repo root and "
        "accepts `.antigravity/settings.json` without startup failure.\n"
    )
    text[R(".antigravity/AGENTS.md")] = (
        f"<!-- {GENERATED} -->\n# Antigravity Context Adapter\n\n"
        "Read `../AGENTS.md` and `../.agents/**`; those files are canonical. Do not duplicate "
        "repository instructions in this adapter.\n"
    )

    jsonf[R(".claude/settings.json")] = claude_settings(permissions)
    jsonf[R(".mcp.json")] = mcp_servers_json(mcp, "claude", ph)
    jsonf[R("opencode.json")] = opencode_config(mcp, permissions, ph)
    jsonf[R(".kiro/settings/mcp.json")] = mcp_servers_json(mcp, "kiro", ph)
    jsonf[R(f".kiro/agents/{name}-maintainer.json")] = kiro_agent(permissions, name)
    jsonf[R(".antigravity/settings.json")] = {
        "__generated": GENERATED,
        "context": {"fileName": "AGENTS.md"},
        **mcp_servers_json(mcp, "antigravity", ph),
    }
    return text, jsonf


def json_text(data: dict[str, Any]) -> str:
    return json.dumps(data, indent=2, sort_keys=True) + "\n"


def read_existing(path: Path) -> str | None:
    if not path.exists() or path.is_dir():
        return None
    return path.read_text(encoding="utf-8")


def write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def ensure_skill_symlink(root: Path, link_rel: str, check: bool, mismatches: list[str]) -> None:
    """Expose canonical .agents/skills to a provider via a generated symlink."""
    path = root / link_rel
    expected_target = Path("../.agents/skills")
    expected_resolved = (path.parent / expected_target).resolve()

    if check:
        if not path.is_symlink():
            mismatches.append(f"{link_rel} is not a symlink to .agents/skills")
            return
        actual_resolved = (path.parent / os.readlink(path)).resolve()
        if actual_resolved != expected_resolved:
            mismatches.append(f"{link_rel} points to the wrong target")
        return

    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() or path.is_symlink():
        if path.is_symlink() or path.is_file():
            path.unlink()
        else:
            raise SystemExit(
                f"{link_rel} exists as a directory. Remove it or replace it with a symlink "
                "to .agents/skills."
            )
    path.symlink_to(expected_target)


def sync(root: Path, check: bool) -> list[str]:
    """Generate (or check) all adapters. Returns a list of out-of-sync paths."""
    text_files, json_files = build_outputs(root)
    mismatches: list[str] = []

    for path, content in sorted(text_files.items(), key=lambda kv: str(kv[0])):
        if read_existing(path) != content:
            if check:
                mismatches.append(str(path.relative_to(root)))
            else:
                write_text(path, content)

    for path, data in sorted(json_files.items(), key=lambda kv: str(kv[0])):
        content = json_text(data)
        if read_existing(path) != content:
            if check:
                mismatches.append(str(path.relative_to(root)))
            else:
                write_text(path, content)

    ensure_skill_symlink(root, ".claude/skills", check, mismatches)
    ensure_skill_symlink(root, ".kiro/skills", check, mismatches)
    return mismatches
